function [success] = amt_datarepository(data_n,varargin )




%% ------ Check input options --------------------------------------------

    definput.import={'amtredofile'};
    definput.keyvals.FontSize = 12;
    definput.keyvals.MarkerSize = 6;
    definput.flags.type = {'missingflag','baumgartner2013'};
    definput.flags.files = {'ARI_NH12_hrtf_M_dtf_256','ARI_NH14_hrtf_M_dtf_256','ARI_NH15_hrtf_M_dtf_256',...
        'ARI_NH16_hrtf_M_dtf_256','ARI_NH17_hrtf_M_dtf_256','ARI_NH18_hrtf_M_dtf_256','ARI_NH21_hrtf_M_dtf_256',...
        'ARI_NH22_hrtf_M_dtf_256','ARI_NH33_hrtf_M_dtf_256','ARI_NH39_hrtf_M_dtf_256','ARI_NH41_hrtf_M_dtf_256',...
        'ARI_NH42_hrtf_M_dtf_256','ARI_NH43_hrtf_M_dtf_256','ARI_NH46_hrtf_M_dtf_256','ARI_NH53_hrtf_M_dtf_256',...
        'ARI_NH55_hrtf_M_dtf_256','ARI_NH57_hrtf_M_dtf_256','ARI_NH58_hrtf_M_dtf_256','ARI_NH62_hrtf_M_dtf_256',...
        'ARI_NH64_hrtf_M_dtf_256','ARI_NH68_hrtf_M_dtf_256','ARI_NH71_hrtf_M_dtf_256','ARI_NH72_hrtf_M_dtf_256'};
    
    [flags,~]  = ltfatarghelper({'FontSize','MarkerSize'},definput,varargin);

    if flags.do_missingflag
      flagnames=[sprintf('%s, ',definput.flags.type{2:end-2}),...
                 sprintf('%s or %s',definput.flags.type{end-1},definput.flags.type{end})];
      error('%s: You must specify one of the following flags: %s.',upper(mfilename),flagnames);
    end;
      
    
%% Baumgartner 2013

  if flags.do_baumgartner2013 
    tic;
    % Database
    database_url = { ...
    'ARI_NH12_hrtf_M_dtf 256', 'http://sourceforge.net/projects/amtoolbox/files/Data/required/hrtf/baumgartner2013/ARI_NH12_hrtf_M_dtf%20256.sofa/download';...
    'ARI_NH14_hrtf_M_dtf 256', 'http://sourceforge.net/projects/amtoolbox/files/Data/required/hrtf/baumgartner2013/ARI_NH14_hrtf_M_dtf%20256.sofa/download';...
    'ARI_NH15_hrtf_M_dtf 256', 'http://sourceforge.net/projects/amtoolbox/files/Data/required/hrtf/baumgartner2013/ARI_NH15_hrtf_M_dtf%20256.sofa/download';...
    'ARI_NH16_hrtf_M_dtf 256', 'http://sourceforge.net/projects/amtoolbox/files/Data/required/hrtf/baumgartner2013/ARI_NH16_hrtf_M_dtf%20256.sofa/download';...
    'ARI_NH17_hrtf_M_dtf 256', 'http://sourceforge.net/projects/amtoolbox/files/Data/required/hrtf/baumgartner2013/ARI_NH17_hrtf_M_dtf%20256.sofa/download';...
    'ARI_NH18_hrtf_M_dtf 256', 'http://sourceforge.net/projects/amtoolbox/files/Data/required/hrtf/baumgartner2013/ARI_NH18_hrtf_M_dtf%20256.sofa/download';...
    'ARI_NH21_hrtf_M_dtf 256', 'http://sourceforge.net/projects/amtoolbox/files/Data/required/hrtf/baumgartner2013/ARI_NH21_hrtf_M_dtf%20256.sofa/download';...
    'ARI_NH22_hrtf_M_dtf 256', 'http://sourceforge.net/projects/amtoolbox/files/Data/required/hrtf/baumgartner2013/ARI_NH22_hrtf_M_dtf%20256.sofa/download';...
    'ARI_NH33_hrtf_M_dtf 256', 'http://sourceforge.net/projects/amtoolbox/files/Data/required/hrtf/baumgartner2013/ARI_NH33_hrtf_M_dtf%20256.sofa/download';...
    'ARI_NH39_hrtf_M_dtf 256', 'http://sourceforge.net/projects/amtoolbox/files/Data/required/hrtf/baumgartner2013/ARI_NH39_hrtf_M_dtf%20256.sofa/download';...
    'ARI_NH41_hrtf_M_dtf 256', 'http://sourceforge.net/projects/amtoolbox/files/Data/required/hrtf/baumgartner2013/ARI_NH41_hrtf_M_dtf%20256.sofa/download';...
    'ARI_NH42_hrtf_M_dtf 256', 'http://sourceforge.net/projects/amtoolbox/files/Data/required/hrtf/baumgartner2013/ARI_NH42_hrtf_M_dtf%20256.sofa/download';...
    'ARI_NH43_hrtf_M_dtf 256', 'http://sourceforge.net/projects/amtoolbox/files/Data/required/hrtf/baumgartner2013/ARI_NH43_hrtf_M_dtf%20256.sofa/download';...
    'ARI_NH46_hrtf_M_dtf 256', 'http://sourceforge.net/projects/amtoolbox/files/Data/required/hrtf/baumgartner2013/ARI_NH46_hrtf_M_dtf%20256.sofa/download';...
    'ARI_NH53_hrtf_M_dtf 256', 'http://sourceforge.net/projects/amtoolbox/files/Data/required/hrtf/baumgartner2013/ARI_NH53_hrtf_M_dtf%20256.sofa/download';...
    'ARI_NH55_hrtf_M_dtf 256', 'http://sourceforge.net/projects/amtoolbox/files/Data/required/hrtf/baumgartner2013/ARI_NH55_hrtf_M_dtf%20256.sofa/download';...
    'ARI_NH57_hrtf_M_dtf 256', 'http://sourceforge.net/projects/amtoolbox/files/Data/required/hrtf/baumgartner2013/ARI_NH57_hrtf_M_dtf%20256.sofa/download';...
    'ARI_NH58_hrtf_M_dtf 256', 'http://sourceforge.net/projects/amtoolbox/files/Data/required/hrtf/baumgartner2013/ARI_NH58_hrtf_M_dtf%20256.sofa/download';...
    'ARI_NH62_hrtf_M_dtf 256', 'http://sourceforge.net/projects/amtoolbox/files/Data/required/hrtf/baumgartner2013/ARI_NH62_hrtf_M_dtf%20256.sofa/download';...
    'ARI_NH64_hrtf_M_dtf 256', 'http://sourceforge.net/projects/amtoolbox/files/Data/required/hrtf/baumgartner2013/ARI_NH64_hrtf_M_dtf%20256.sofa/download';...
    'ARI_NH68_hrtf_M_dtf 256', 'http://sourceforge.net/projects/amtoolbox/files/Data/required/hrtf/baumgartner2013/ARI_NH68_hrtf_M_dtf%20256.sofa/download';...
    'ARI_NH71_hrtf_M_dtf 256', 'http://sourceforge.net/projects/amtoolbox/files/Data/required/hrtf/baumgartner2013/ARI_NH71_hrtf_M_dtf%20256.sofa/download';...
    'ARI_NH72_hrtf_M_dtf 256', 'http://sourceforge.net/projects/amtoolbox/files/Data/required/hrtf/baumgartner2013/ARI_NH72_hrtf_M_dtf%20256.sofa/download';...  
    }; 

    % Downloading
    % get to the path hrtf/
    basepath = fullfile(amtbasepath,'required','hrtf','baumgartner2013');
    
    % create directory if it is not existing
    if ~exist(basepath,'dir')
        mkdir(basepath);
    end;
    
    ii = data_n;
    % check if file is already downloaded
    filename = fullfile(basepath,[database_url{ii,1} '.mat']);
        if ~exist(filename,'file')
            success = urlwrite(database_url{ii,2},filename);
        else
            success = 1;
        end
  toc;
  end
        
