function definput=arg_localizationerror(definput)

definput.flags.errorflag = {'','accL','precL','precLcentral','accP','precP','querr','accE',...
  'absaccE','absaccL','accabsL','accPnoquerr','precE','querr90','accE','precPmedian',...
  'precPmedianlocal','precPnoquerr','rmsL','rmsPmedianlocal','rmsPmedian',...
  'querrMiddlebrooks','corrcoefL','corrcoefP','SCC',...
  'gainLstats','gainL','pVeridicalL','precLregress'...
  'sirpMacpherson2000','gainPfront','gainPrear','gainP','perMacpherson2003',...
  'pVeridicalPfront','pVeridicalPrear','pVeridicalP','precPregressFront','precPregressRear'};
definput.keyvals.f=[];       % regress structure of frontal hemisphere
definput.keyvals.r=[];       % regress structure of rear hemisphere

end